# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Cleans project"
  lane :clean do
    gradle(task: "clean")
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Release a new Internal Build to Google Play Store"
  lane :releaseInternal do
    clean
    test

    # automatic bump version

    gradle(
        task: 'assemble',
        build_type: 'Release',
        print_command: true
    )
    upload_to_play_store(track: 'internal')
  end
end
