# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Cleans project"
  lane :clean do
    gradle(task: "clean")
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Bump SemVer version"
  lane :bumpSemverVersion do |options|
    properties = {
        "bump" => options[:bump],
        "versionKey" => "APPLICATION_VERSION"
    }

    gradle(
        task: 'bumpSemverVersion',
        properties: properties
    )
  end

  private_lane :commit_build_bump do |options|
    begin
      git_commit(
        path: "./app/build.gradle",
        message: "[skip ci]: version bump #{options[:version]}"
      )
    rescue
      UI.message "app/build.gradle was not changed with the bumped version, commit failed"
    end
  end

  desc "Release a new Internal Build to Google Play Store"
  lane :release do |options|
    clean
    test
    bumpSemverVersion(bump: options[:bump])
    assemble(buildType: 'Release')
    upload_to_play_store(track: options[:track])
  end

  desc "Assemble"
    lane :assemble do |options|
      puts "Assemble #{options[:buildType]}"
      gradle(
          task: 'assemble',
          build_type: options[:buildType]
      )
    end
end
